# Generated by Django 4.2.7 on 2026-02-20 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card_number',
            field=models.CharField(blank=True, help_text='National ID or Voter ID number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_proof',
            field=models.ImageField(blank=True, help_text='Upload ID card image', null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin verification status'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
