# Generated by Django 4.2.7 on 2026-02-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_user_id_card_number_user_id_card_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card_proof',
            field=models.FileField(blank=True, help_text='Upload ID card image', null=True, upload_to='id_proofs/'),
        ),
    ]
